name: PR Checks
on: pull_request
jobs:
  build:
    runs-on: ubuntu-${{ vars.UBUNTU_VERSION }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Setup Node.js ${{ vars.NODE_LTS_ACTIVE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ vars.NODE_LTS_ACTIVE_VERSION }}
      - name: Generate types
        run: pnpm generate-types
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
